// <auto-generated />
using System;
using Bookstore.Services.Discount.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bookstore.Services.Discount.Migrations
{
    [DbContext(typeof(DiscountDbContext))]
    [Migration("20210313211349_InitialDiscount")]
    partial class InitialDiscount
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Bookstore.Services.Discount.Entities.Coupon", b =>
                {
                    b.Property<Guid>("CouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AlreadyUsed")
                        .HasColumnType("bit");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CouponId");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            CouponId = new Guid("0be058a4-72ad-406e-9e52-40ef9f2f0423"),
                            AlreadyUsed = false,
                            Amount = 10,
                            Code = "SuperKsiazka"
                        },
                        new
                        {
                            CouponId = new Guid("b71f0000-a7ea-418d-902f-7aa0f4c977c3"),
                            AlreadyUsed = false,
                            Amount = 20,
                            Code = "Wow"
                        },
                        new
                        {
                            CouponId = new Guid("a52b3dde-d046-4e75-bf6c-3368b7fd8204"),
                            AlreadyUsed = false,
                            Amount = 100,
                            Code = "WszystkoZaDarmo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
